### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by ianling** [SigNoz/sample-golang-app#1]
The API provided by the upstream opentelemetry repos appears to have changed, so this project can no longer be referenced as an example when integrating opentelemetry and SigNoz into an existing Go application.

It would be very helpful if this application could be updated to use the latest versions of all the opentelemetry dependencies.

**Comment by pranay01** [comment]
thanks for creating the issue @ianling

**Comment by ankitnayan** [comment]
Updating otel-go libs at https://github.com/SigNoz/sample-golang-app/blob/master/go.mod

**Comment by makeavish** [comment]
Updated otel-go libs in latest commit: https://github.com/SigNoz/sample-golang-app/commit/c3b1266147cd3c2030ef7a5f1f50b60eff126188
